### PR TITLE
Sofian bahri

### PR DESCRIPTION
**Pull request by thekeyagent**
The naive function is not using asynchronous in looping. It will be fine if your data is not big. But there is S3 function that can need more time to wait then generate local log.
There is generated log with Date() as name on bucket directory if the code can be executed.

### CODE REVIEW

**Comment by thekeyagent** [comment]
log has been added

**Comment by diorahman** [comment]
I can see in several places you changed the es2015 features to be relevant to previous es version. Do you have valid reason for this? 

I hope you want to try the es2015! Please read this if you have time: https://ponyfoo.com/articles/es6

ISTM you didn't run any style check which is unfortunate. I know you can do better than this :smile: 

Do you want to submit another shot?

**Comment by thekeyagent** [comment]
Thanks for your review.
Aaahhh, ok 
im using 4th version of nodejs.
It seems latest version is 5th

Ok, i will change it to es6.

**Comment by diorahman** [comment]
Thank you @thekeyagent for your time for doing this! We will have an internal meeting for making the decision. We will contact you as soon as possible.

**Pull request closed without merging**
