### PR TITLE
my solutions

### PR DESCRIPTION
**Pull request by lukluk**
> What do you think about the naive() function?

```
//LINE 15
for (let index in parsed) { 
```
not need 
```
//LINE 45
index++
```
also you missed to debug success msg

### CODE REVIEW

**Comment by lukluk** [comment]
here  :dancer:

**Comment by lukluk** [comment]
sorry @diorahman  you not decide any code style standart so my editor setting replace your code style

**Comment by lukluk** [comment]
just commited code with jscs test

**Comment by lukluk** [comment]
@diorahman are you bussy?

**Comment by diorahman** [comment]
Hi @lukluk thank you for submitting this PR! Can you put all of these commits into a single commit and explain it in the comments? Also I'm not sure I clearly understand regarding your comments on the `naive()` function, can you elaborate more about that?

**Comment by lukluk** [comment]
Ok, i will close this pr and  submit new

**Pull request closed without merging**
