### PR TITLE
Add parse-async, parse-promise and parse-stream

### PR DESCRIPTION
**Pull request by aldidana**

### CODE REVIEW

**Comment by diorahman** [comment]
Hi Aldi, thank you for this.

Do you think this one https://github.com/HOOQsters/hello-csv/blob/master/parse-callback.js#L46 is OK?

**Comment by aldidana** [comment]
hi @diorahman 
sorry, there is no need for index++, because parsed is object not an array.

**Comment by diorahman** [comment]
> sorry, there is no need for index++, because parsed is object not an array.
So @aldidana, do you mean: the `parsed` here ihttps://github.com/HOOQsters/hello-csv/blob/master/parse-callback.js#L14 is not an Array? Are you sure? How do you check if an object is an Array or not?

Anyway, could you design and implement some of the necessary unit tests for this?

Thanks!

**Comment by aldidana** [comment]
I just tried parse-callback.js and parsed is an array (sorry if i'm mistaken) also we still don't need index++ because it was increment by itself.

i will do unit testing tonight @diorahman

**Comment by diorahman** [comment]
Hi @aldidana Thanks for this! We will have internal discussion and get back to you.

**Pull request closed without merging**
